### ISSUE TITLE
PHP GD crush

### ISSUE THREAD

**Issue by bolknote** [remicollet/remirepo#204]
Hello!

OS: CentOS Linux release 7.6.1810 (Core) or CentOS Linux release 7.4.1708 (Core)
PHP: 7.4.29 (remi)

Code for reproduce: 

```
        $imageHandler = imagecreatefrompng('somepngfile.png');
        $fgcolor = imagecolorallocate($imageHandler, 0, 0, 0);
        $font='/usr/share/fonts/msttcorefonts/arial.ttf';
        var_dump(imagettftext(
            $imageHandler,
            18,
            0,
            40,
            180,
            $fgcolor,
            $font,
            'риве'
        ));
	var_dump(error_get_last());
        imagepng($imageHandler, '/tmp/test.png');
```

GDB backtrace:

```
(gdb) bt
#0  0x00007fffe9a8fddd in gdImageStringFTEx (im=im@entry=0x55555604a180, brect=brect@entry=0x7fffffffaa30, fg=0, fontlist=<optimized out>, ptsize=18, angle=<optimized out>, x=40, y=180,
    string=string@entry=0x7fffd167acd8 "риве", strex=strex@entry=0x0) at gdft.c:1400
#1  0x00007fffe9a90c5b in gdImageStringFT (im=im@entry=0x55555604a180, brect=brect@entry=0x7fffffffaa30, fg=<optimized out>, fontlist=<optimized out>, ptsize=<optimized out>, angle=<optimized out>,
    x=<optimized out>, y=<optimized out>, string=0x7fffd167acd8 "риве") at gdft.c:932
#2  0x00007fffe9cd88f8 in php_imagettftext_common.isra.10 () at /usr/src/debug/php-7.4.29/ext/gd/gd.c:4120
#3  0x00005555558d4df8 in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.4.29/Zend/zend_vm_execute.h:1314
#4  execute_ex () at /usr/src/debug/php-7.4.29/Zend/zend_vm_execute.h:53501
#5  0x00005555558da111 in zend_execute (op_array=0x7ffff3c762a0, return_value=<optimized out>) at /usr/src/debug/php-7.4.29/Zend/zend_vm_execute.h:57617
#6  0x0000555555852e63 in zend_execute_scripts () at /usr/src/debug/php-7.4.29/Zend/zend.c:1679
#7  0x00005555557f15c0 in php_execute_script () at /usr/src/debug/php-7.4.29/main/main.c:2674
#8  0x00005555558dc29c in do_cli (argc=2, argv=0x555555d73d00) at /usr/src/debug/php-7.4.29/sapi/cli/php_cli.c:964
#9  0x000055555565781b in main (argc=2, argv=0x555555d73d00) at /usr/src/debug/php-7.4.29/sapi/cli/php_cli.c:1360
(gdb) quit
```

Thank you in advance!

**Comment by oleg-st** [comment]
Works fine with php 7.4.25
Possible related to #194

**Comment by remicollet** [comment]
Using
```
gd-last-2.3.3-2.el7.remi.x86_64
freetype-2.8-14.el7_9.1.x86_64
```

**Comment by bolknote** [comment]
It seems to be because of the GD version. When I upgraded from gd-last-2.2.5 to gd-last-2.3.3, the bug disappeared.

**Comment by bolknote** [comment]
But PHP 7.4.25 (CentOS Linux release 7.4.1708) still crushing.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe9a9addd in gdImageStringFTEx () from /lib64/libgd.so.3
(gdb) bt
#0  0x00007fffe9a9addd in gdImageStringFTEx () from /lib64/libgd.so.3
#1  0x00007fffe9a9bc5b in gdImageStringFT () from /lib64/libgd.so.3
#2  0x00007fffe9ce38f8 in php_imagettftext_common.isra.10 () from /usr/lib64/php/modules/gd.so
#3  0x00005555558d49e8 in execute_ex ()
#4  0x00005555558d9d01 in zend_execute ()
#5  0x0000555555852a73 in zend_execute_scripts ()
#6  0x00005555557f11e0 in php_execute_script ()
#7  0x00005555558dbe8c in do_cli ()
#8  0x00005555556577eb in main ()
```

```
]# rpm -qa|egrep 'gd-last|freetype'
gd-last-2.3.3-2.el7.remi.x86_64
freetype-2.9.1-4.el7.centos.x86_64
```

```
# php --ri gd

gd

GD Support => enabled
GD headers Version => 2.3.3
GD library Version => 2.3.3
FreeType Support => enabled
FreeType Linkage => with freetype
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

**Comment by remicollet** [comment]
> CentOS Linux release 7.4.1708

Sorry but cannot support old versions (see repository FAQ)
Only latest (7.9) with all update

> freetype-2.9.1-4.el7.centos.x86_64

No idea where this come from, official is freetype-2.8-14.el7

**Comment by bolknote** [comment]
Okay, IC. Well, then I'll close the issue.
